BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Spells" (
	"SpellName"	TEXT NOT NULL,
	"Level"	INTEGER NOT NULL,
	"Class"	INTEGER
);
CREATE TABLE IF NOT EXISTS "races" (
	"id"	INTEGER NOT NULL UNIQUE,
	"race"	TEXT NOT NULL,
	"size"	TEXT NOT NULL,
	"speed"	TEXT NOT NULL,
	"type"	TEXT NOT NULL,
	"strength"	TEXT,
	"constitution"	TEXT,
	"dexterity"	TEXT,
	"intelligence"	TEXT,
	"wisdom"	TEXT,
	"charisma"	TEXT,
	"language1"	TEXT,
	"language2"	TEXT,
	"language3"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "classes" (
	"Name"	TEXT
);
INSERT INTO "Spells" VALUES ('Vicious Mockery',1,'Bard');
INSERT INTO "Spells" VALUES ('Cure Wounds',1,'Bard');
INSERT INTO "Spells" VALUES ('Dissonant Whispers',1,'Bard');
INSERT INTO "Spells" VALUES ('Heat Metal',2,'Bard');
INSERT INTO "Spells" VALUES ('Counterspell',3,'Bard');
INSERT INTO "Spells" VALUES ('Bless',1,'Cleric');
INSERT INTO "Spells" VALUES ('Heal',2,'Cleric');
INSERT INTO "Spells" VALUES ('Magic Missile',1,'Wizard');
INSERT INTO "Spells" VALUES ('Fireball',3,'Wizard');
INSERT INTO "Spells" VALUES ('Bane',1,'Bard');
INSERT INTO "Spells" VALUES ('Charm Person',1,'Bard');
INSERT INTO "Spells" VALUES ('Charm Person',1,'Bard');
INSERT INTO "Spells" VALUES ('Comprehend Languages',1,'Bard');
INSERT INTO "Spells" VALUES ('Cure Wounds',1,'Bard');
INSERT INTO "Spells" VALUES ('Detect Magic',1,'Bard');
INSERT INTO "Spells" VALUES ('Disguise Self',1,'Bard');
INSERT INTO "Spells" VALUES ('Dissonant Whispers',1,'Bard');
INSERT INTO "Spells" VALUES ('Faerie Fire',1,'Bard');
INSERT INTO "Spells" VALUES ('Feather Fall',1,'Bard');
INSERT INTO "Spells" VALUES ('Healing Word',1,'Bard');
INSERT INTO "Spells" VALUES ('Heroism',1,'Bard');
INSERT INTO "Spells" VALUES ('Identify
',1,'Bard');
INSERT INTO "Spells" VALUES ('Longstrider',1,'Bard');
INSERT INTO "Spells" VALUES ('Silent Image',1,'Bard');
INSERT INTO "Spells" VALUES ('Sleep',1,'Bard');
INSERT INTO "Spells" VALUES ('Speak with Animals',1,'Bard');
INSERT INTO "Spells" VALUES ('Hideous Laughter',1,'Bard');
INSERT INTO "Spells" VALUES ('Thunderwave',1,'Bard');
INSERT INTO "Spells" VALUES ('Unseen Servant',1,'Bard');
INSERT INTO "Spells" VALUES ('Animal Messenger',2,'Bard');
INSERT INTO "Spells" VALUES ('Blindness/Deafness',2,'Bard');
INSERT INTO "Spells" VALUES ('Calm Emotions',2,'Bard');
INSERT INTO "Spells" VALUES ('Cloud of Daggers',2,'Bard');
INSERT INTO "Spells" VALUES ('Crown of Madness',2,'Bard');
INSERT INTO "Spells" VALUES ('Detect Thoughts',2,'Bard');
INSERT INTO "Spells" VALUES ('Enhance Ability',2,'Bard');
INSERT INTO "Spells" VALUES ('Enthrall',2,'Bard');
INSERT INTO "Spells" VALUES ('Heat Metal',2,'Bard');
INSERT INTO "Spells" VALUES ('Hold Person',2,'Bard');
INSERT INTO "Spells" VALUES ('Invisibility',2,'Bard');
INSERT INTO "Spells" VALUES ('Knock',2,'Bard');
INSERT INTO "Spells" VALUES ('Lesser Restoration',2,'Bard');
INSERT INTO "Spells" VALUES ('Locate Animals or Plants',2,'Bard');
INSERT INTO "Spells" VALUES ('Locate Object',2,'Bard');
INSERT INTO "Spells" VALUES ('Magic Mouth',2,'Bard');
INSERT INTO "Spells" VALUES ('Phantasmal Force',2,'Bard');
INSERT INTO "Spells" VALUES ('Pyrotechnics',2,'Bard');
INSERT INTO "Spells" VALUES ('See Invisibility',2,'Bard');
INSERT INTO "Spells" VALUES ('Shatter',2,'Bard');
INSERT INTO "Spells" VALUES ('Silence',2,'Bard');
INSERT INTO "Spells" VALUES ('Suggestion',2,'Bard');
INSERT INTO "Spells" VALUES ('Zone of Truth
',2,'Bard');
INSERT INTO "Spells" VALUES ('Bestow Curse',3,'Bard');
INSERT INTO "Spells" VALUES ('Clairvoyance',3,'Bard');
INSERT INTO "Spells" VALUES ('Counterspell
',3,'Bard');
INSERT INTO "Spells" VALUES ('Crusader''s Mantle',3,'Bard');
INSERT INTO "Spells" VALUES ('Mass Cure Wounds ',3,'Bard');
INSERT INTO "Spells" VALUES ('Daylight',3,'Bard');
INSERT INTO "Spells" VALUES ('Dispel Magic',3,'Bard');
INSERT INTO "Spells" VALUES ('Enemies Abound',3,'Bard');
INSERT INTO "Spells" VALUES ('Fear',3,'Bard');
INSERT INTO "Spells" VALUES ('Feign Death',3,'Bard');
INSERT INTO "Spells" VALUES ('Fireball',3,'Bard');
INSERT INTO "Spells" VALUES ('Flame Arrows',3,'Bard');
INSERT INTO "Spells" VALUES ('Fly',3,'Bard');
INSERT INTO "Spells" VALUES ('Gaseous Form',3,'Bard');
INSERT INTO "Spells" VALUES ('Glyph of Warding',3,'Bard');
INSERT INTO "Spells" VALUES ('Haste',3,'Bard');
INSERT INTO "Spells" VALUES ('Hypnotic Pattern',3,'Bard');
INSERT INTO "Spells" VALUES ('Tiny Hut',3,'Bard');
INSERT INTO "Spells" VALUES ('Lightning Bolt',3,'Bard');
INSERT INTO "Spells" VALUES ('Major Image',3,'Bard');
INSERT INTO "Spells" VALUES ('Nondetection',3,'Bard');
INSERT INTO "Spells" VALUES ('Plant Growth',3,'Bard');
INSERT INTO "Spells" VALUES ('Protection from Energy',3,'Bard');
INSERT INTO "Spells" VALUES ('Remove Curse',3,'Bard');
INSERT INTO "Spells" VALUES ('Sending',3,'Bard');
INSERT INTO "Spells" VALUES ('Sleet Storm',3,'Bard');
INSERT INTO "Spells" VALUES ('Slow',3,'Bard');
INSERT INTO "Spells" VALUES ('Speak with Dead',3,'Bard');
INSERT INTO "Spells" VALUES ('Stinking Cloud',3,'Bard');
INSERT INTO "Spells" VALUES ('Tongues',3,'Bard');
INSERT INTO "Spells" VALUES ('Vampiric Touch',3,'Bard');
INSERT INTO "Spells" VALUES ('Water Walk',3,'Bard');
INSERT INTO "Spells" VALUES ('Arcane Eye',4,'Bard');
INSERT INTO "Spells" VALUES ('Banishment',4,'Bard');
INSERT INTO "Spells" VALUES ('Blinding Smite',4,'Bard');
INSERT INTO "Spells" VALUES ('Compulsion
',4,'Bard');
INSERT INTO "Spells" VALUES ('Confusion',4,'Bard');
INSERT INTO "Spells" VALUES ('Conjure Minor Elementals',4,'Bard');
INSERT INTO "Spells" VALUES ('Control Water',4,'Bard');
INSERT INTO "Spells" VALUES ('Control Weather',4,'Bard');
INSERT INTO "Spells" VALUES ('Dimension Door
',4,'Bard');
INSERT INTO "Spells" VALUES ('Dominate Beast',4,'Bard');
INSERT INTO "Spells" VALUES ('Evard''s Black Tentacles',4,'Bard');
INSERT INTO "Spells" VALUES ('Fabricate',4,'Bard');
INSERT INTO "Spells" VALUES ('Freedom of Movement',4,'Bard');
INSERT INTO "Spells" VALUES ('Greater Invisibility',4,'Bard');
INSERT INTO "Spells" VALUES ('Guardian of Faith',4,'Bard');
INSERT INTO "Spells" VALUES ('Hallucinatory Terrain',4,'Bard');
INSERT INTO "Spells" VALUES ('Ice Storm',4,'Bard');
INSERT INTO "Spells" VALUES ('Secret Chest',4,'Bard');
INSERT INTO "Spells" VALUES ('Locate Creature',4,'Bard');
INSERT INTO "Spells" VALUES ('Private Sanctum',4,'Bard');
INSERT INTO "Spells" VALUES ('Resilient Sphere',4,'Bard');
INSERT INTO "Spells" VALUES ('Phantasmal Killer',4,'Bard');
INSERT INTO "Spells" VALUES ('Polymorph',4,'Bard');
INSERT INTO "Spells" VALUES ('Resilient Sphere',4,'Bard');
INSERT INTO "Spells" VALUES ('Shadow of Moil',4,'Bard');
INSERT INTO "Spells" VALUES ('Stone Shape',4,'Bard');
INSERT INTO "Spells" VALUES ('Stoneskin',4,'Bard');
INSERT INTO "Spells" VALUES ('Storm Sphere',4,'Bard');
INSERT INTO "Spells" VALUES ('Staggering Smite',4,'Bard');
INSERT INTO "Spells" VALUES ('Summon Greater Demon',4,'Bard');
INSERT INTO "Spells" VALUES ('Vitriolic Sphere',4,'Bard');
INSERT INTO "Spells" VALUES ('Wall of Fire',4,'Bard');
INSERT INTO "Spells" VALUES ('Animate Objects',5,'Bard');
INSERT INTO "Spells" VALUES ('Awaken',5,'Bard');
INSERT INTO "Spells" VALUES ('Bigby''s Hand',5,'Bard');
INSERT INTO "Spells" VALUES ('Circle of Power',5,'Bard');
INSERT INTO "Spells" VALUES ('Cloudkill',5,'Bard');
INSERT INTO "Spells" VALUES ('Commune',5,'Bard');
INSERT INTO "Spells" VALUES ('Commune with Nature',5,'Bard');
INSERT INTO "Spells" VALUES ('Cone of Cold',5,'Bard');
INSERT INTO "Spells" VALUES ('Conjure Elemental',5,'Bard');
INSERT INTO "Spells" VALUES ('Contact Other Plane',5,'Bard');
INSERT INTO "Spells" VALUES ('Contagion',5,'Bard');
INSERT INTO "Spells" VALUES ('Control Winds',5,'Bard');
INSERT INTO "Spells" VALUES ('Creation',5,'Bard');
INSERT INTO "Spells" VALUES ('Destructive Wave',5,'Bard');
INSERT INTO "Spells" VALUES ('Dominate Person',5,'Bard');
INSERT INTO "Spells" VALUES ('Dream',5,'Bard');
INSERT INTO "Spells" VALUES ('Enervation',5,'Bard');
INSERT INTO "Spells" VALUES ('Far Step',5,'Bard');
INSERT INTO "Spells" VALUES ('Flame Strike',5,'Bard');
INSERT INTO "Spells" VALUES ('Geas',5,'Bard');
INSERT INTO "Spells" VALUES ('Greater Restoration',5,'Bard');
INSERT INTO "Spells" VALUES ('Hold Monster',5,'Bard');
INSERT INTO "Spells" VALUES ('Immolation',5,'Bard');
INSERT INTO "Spells" VALUES ('Infernal Calling',5,'Bard');
INSERT INTO "Spells" VALUES ('Legend Lore',5,'Bard');
INSERT INTO "Spells" VALUES ('Mass Cure Wounds',5,'Bard');
INSERT INTO "Spells" VALUES ('Mislead',5,'Bard');
INSERT INTO "Spells" VALUES ('Modify Memory',5,'Bard');
INSERT INTO "Spells" VALUES ('Passwall',5,'Bard');
INSERT INTO "Spells" VALUES ('Planar Binding',5,'Bard');
INSERT INTO "Spells" VALUES ('Rary''s Telepathic Bond',5,'Bard');
INSERT INTO "Spells" VALUES ('Reincarnate',5,'Bard');
INSERT INTO "Spells" VALUES ('Scrying',5,'Bard');
INSERT INTO "Spells" VALUES ('Seeming',5,'Bard');
INSERT INTO "Spells" VALUES ('Skill Empowerment',5,'Bard');
INSERT INTO "Spells" VALUES ('Teleportation Circle',5,'Bard');
INSERT INTO "Spells" VALUES ('Teleport',5,'Bard');
INSERT INTO "Spells" VALUES ('Tree Stride',5,'Bard');
INSERT INTO "Spells" VALUES ('Wall of Force',5,'Bard');
INSERT INTO "Spells" VALUES ('Wall of Stone',5,'Bard');
INSERT INTO "Spells" VALUES ('Eyebite',6,'Bard');
INSERT INTO "Spells" VALUES ('Find the Path',6,'Bard');
INSERT INTO "Spells" VALUES ('Forbiddance',6,'Bard');
INSERT INTO "Spells" VALUES ('Geas',6,'Bard');
INSERT INTO "Spells" VALUES ('Globe of Invulnerability',6,'Bard');
INSERT INTO "Spells" VALUES ('Guards and Wards',6,'Bard');
INSERT INTO "Spells" VALUES ('Harm',6,'Bard');
INSERT INTO "Spells" VALUES ('Heal',6,'Bard');
INSERT INTO "Spells" VALUES ('Heroes'' Feast',6,'Bard');
INSERT INTO "Spells" VALUES ('Investiture of Flame',6,'Bard');
INSERT INTO "Spells" VALUES ('Investiture of Ice',6,'Bard');
INSERT INTO "Spells" VALUES ('Investiture of Stone
',6,'Bard');
INSERT INTO "Spells" VALUES ('Investiture of Wind',6,'Bard');
INSERT INTO "Spells" VALUES ('Magic Jar',6,'Bard');
INSERT INTO "Spells" VALUES ('Mass Suggestion',6,'Bard');
INSERT INTO "Spells" VALUES ('Mental Prison',6,'Bard');
INSERT INTO "Spells" VALUES ('Irresistible Dance',6,'Bard');
INSERT INTO "Spells" VALUES ('Planar Ally',6,'Bard');
INSERT INTO "Spells" VALUES ('Programmed Illusion',6,'Bard');
INSERT INTO "Spells" VALUES ('Project Image',6,'Bard');
INSERT INTO "Spells" VALUES ('Sunbeam',6,'Bard');
INSERT INTO "Spells" VALUES ('Otherworldly Guise',6,'Bard');
INSERT INTO "Spells" VALUES ('Teleportation Circle',6,'Bard');
INSERT INTO "Spells" VALUES ('True Seeing',6,'Bard');
INSERT INTO "Spells" VALUES ('Word of Recall',6,'Bard');
INSERT INTO "Spells" VALUES ('Crown of Stars',7,'Bard');
INSERT INTO "Spells" VALUES ('Delayed Blast Fireball',7,'Bard');
INSERT INTO "Spells" VALUES ('Divine Word',7,'Bard');
INSERT INTO "Spells" VALUES ('Etherealness',7,'Bard');
INSERT INTO "Spells" VALUES ('Finger of Death',7,'Bard');
INSERT INTO "Spells" VALUES ('Forcecage',7,'Bard');
INSERT INTO "Spells" VALUES ('Mirage Arcane',7,'Bard');
INSERT INTO "Spells" VALUES ('Magnificent Mansion',7,'Bard');
INSERT INTO "Spells" VALUES ('Sword',7,'Bard');
INSERT INTO "Spells" VALUES ('Plane Shift',7,'Bard');
INSERT INTO "Spells" VALUES ('Power Word Pain',7,'Bard');
INSERT INTO "Spells" VALUES ('Project Image',7,'Bard');
INSERT INTO "Spells" VALUES ('Regenerate',7,'Bard');
INSERT INTO "Spells" VALUES ('Resurrection',7,'Bard');
INSERT INTO "Spells" VALUES ('Reverse Gravity',7,'Bard');
INSERT INTO "Spells" VALUES ('Sequester',7,'Bard');
INSERT INTO "Spells" VALUES ('Simulacrum',7,'Bard');
INSERT INTO "Spells" VALUES ('Symbol',7,'Bard');
INSERT INTO "Spells" VALUES ('Teleport',7,'Bard');
INSERT INTO "Spells" VALUES ('Teleportation Circle',7,'Bard');
INSERT INTO "Spells" VALUES ('Temple of the Gods',7,'Bard');
INSERT INTO "Spells" VALUES ('Thaumaturgy',7,'Bard');
INSERT INTO "Spells" VALUES ('Whirlwind',7,'Bard');
INSERT INTO "Spells" VALUES ('Antimagic Field',8,'Bard');
INSERT INTO "Spells" VALUES ('Antipathy/Sympathy',8,'Bard');
INSERT INTO "Spells" VALUES ('Clone',8,'Bard');
INSERT INTO "Spells" VALUES ('Control Weather',8,'Bard');
INSERT INTO "Spells" VALUES ('Demiplane',8,'Bard');
INSERT INTO "Spells" VALUES ('Dominate Monster',8,'Bard');
INSERT INTO "Spells" VALUES ('Feeblemind',8,'Bard');
INSERT INTO "Spells" VALUES ('Glibness',8,'Bard');
INSERT INTO "Spells" VALUES ('Holy Aura',8,'Bard');
INSERT INTO "Spells" VALUES ('Incendiary Cloud',8,'Bard');
INSERT INTO "Spells" VALUES ('Maze',8,'Bard');
INSERT INTO "Spells" VALUES ('Mind Blank',8,'Bard');
INSERT INTO "Spells" VALUES ('Power Word Stun',8,'Bard');
INSERT INTO "Spells" VALUES ('Sunburst',8,'Bard');
INSERT INTO "Spells" VALUES ('Telepathy',8,'Bard');
INSERT INTO "Spells" VALUES ('Teleportation Circle',8,'Bard');
INSERT INTO "Spells" VALUES ('Astral Projection',9,'Bard');
INSERT INTO "Spells" VALUES ('Foresight',9,'Bard');
INSERT INTO "Spells" VALUES ('Imprisonment',9,'Bard');
INSERT INTO "Spells" VALUES ('Power Word Heal',9,'Bard');
INSERT INTO "Spells" VALUES ('Power Word Kill',9,'Bard');
INSERT INTO "Spells" VALUES ('Prismatic Wall',9,'Bard');
INSERT INTO "Spells" VALUES ('Shapechange',9,'Bard');
INSERT INTO "Spells" VALUES ('Time Stop',9,'Bard');
INSERT INTO "Spells" VALUES ('True Polymorph',9,'Bard');
INSERT INTO "Spells" VALUES ('True Resurrection',9,'Bard');
INSERT INTO "Spells" VALUES ('Wish',9,'Bard');
INSERT INTO "Spells" VALUES ('Bane',1,'Cleric');
INSERT INTO "Spells" VALUES ('Bless',1,'Cleric');
INSERT INTO "Spells" VALUES ('Command',1,'Cleric');
INSERT INTO "Spells" VALUES ('Cure Wounds',1,'Cleric');
INSERT INTO "Spells" VALUES ('Detect Evil and Good ',1,'Cleric');
INSERT INTO "Spells" VALUES ('Detect Magic',1,'Cleric');
INSERT INTO "Spells" VALUES ('Detect Poison and Disease',1,'Cleric');
INSERT INTO "Spells" VALUES ('Guiding Bolt ',1,'Cleric');
INSERT INTO "Spells" VALUES ('Healing Word',1,'Cleric');
INSERT INTO "Spells" VALUES ('Inflict Wounds ',1,'Cleric');
INSERT INTO "Spells" VALUES ('Protection from Evil and Good',1,'Cleric');
INSERT INTO "Spells" VALUES ('Purify Food and Drink ',1,'Cleric');
INSERT INTO "Spells" VALUES ('Sanctuary',1,'Cleric');
INSERT INTO "Spells" VALUES ('Shield of Faith',1,'Cleric');
INSERT INTO "Spells" VALUES ('Silent Image ',1,'Cleric');
INSERT INTO "Spells" VALUES ('Sleep',1,'Cleric');
INSERT INTO "Spells" VALUES ('Speak with Dead',1,'Cleric');
INSERT INTO "Spells" VALUES ('Thunderwave ',1,'Cleric');
INSERT INTO "Spells" VALUES ('Unseen Servant ',1,'Cleric');
INSERT INTO "Spells" VALUES ('Awaken',5,'Druid');
INSERT INTO "Spells" VALUES ('Teleportation Circle',5,'Sorcerer');
INSERT INTO "Spells" VALUES ('Animate Objects',5,'Wizard');
INSERT INTO "Spells" VALUES ('Destructive Wave',5,'Warlock');
INSERT INTO "Spells" VALUES ('Destructive Smite',5,'Paladin');
INSERT INTO "Spells" VALUES ('Swift Quiver',5,'Ranger');
INSERT INTO "Spells" VALUES ('Conjure Animals',3,'Ranger');
INSERT INTO "Spells" VALUES ('Mass Cure Wounds',5,'Ranger');
INSERT INTO "Spells" VALUES ('Daylight',3,'Ranger');
INSERT INTO "Spells" VALUES ('Nondetection',3,'Ranger');
INSERT INTO "Spells" VALUES ('Plant Growth',3,'Ranger');
INSERT INTO "Spells" VALUES ('Protection from Energy',3,'Ranger');
INSERT INTO "Spells" VALUES ('Speak with Plant',3,'Ranger');
INSERT INTO "Spells" VALUES ('Water Walk',3,'Ranger');
INSERT INTO "Spells" VALUES ('Blink',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Clairvoyance',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Counterspell',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Daylight',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Dispel Magic',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Fear',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Fireball',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Fly',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Gaseous Form',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Haste',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Hypnotic Pattern',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Lightning Bolt',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Major Image',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Protection from Energy:',3,'sorcerers');
INSERT INTO "Spells" VALUES ('sleet Storm',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Slow',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Stinking Cloud',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Tongues',3,'sorcerers');
INSERT INTO "Spells" VALUES ('Banishment',4,'Cleric');
INSERT INTO "Spells" VALUES ('Blight',4,'Cleric');
INSERT INTO "Spells" VALUES ('Control Water:',4,'Cleric');
INSERT INTO "Spells" VALUES ('Death Ward',4,'Cleric');
INSERT INTO "Spells" VALUES ('Dimension Door',4,'Cleric');
INSERT INTO "Spells" VALUES ('Divination',4,'Cleric');
INSERT INTO "Spells" VALUES ('Freedom of Movement',4,'Cleric');
INSERT INTO "Spells" VALUES ('Giant Insect',4,'Cleric');
INSERT INTO "Spells" VALUES ('Guardian of Faith',4,'Cleric');
INSERT INTO "Spells" VALUES ('Hallucinatory Terrain',4,'Cleric');
INSERT INTO "Spells" VALUES ('Immovable Object',4,'Cleric');
INSERT INTO "Spells" VALUES ('Locate Creature',4,'Cleric');
INSERT INTO "Spells" VALUES ('Polymorph',4,'Cleric');
INSERT INTO "Spells" VALUES ('Stone Shape',4,'Cleric');
INSERT INTO "Spells" VALUES ('Stoneskin:',4,'Cleric');
INSERT INTO "Spells" VALUES ('Summon Undead',4,'Cleric');
INSERT INTO "Spells" VALUES ('Wall of Fire',4,'Cleric');
INSERT INTO "Spells" VALUES ('Watery Sphere',4,'Cleric');
INSERT INTO "Spells" VALUES ('Aura of Life',4,'paladins');
INSERT INTO "Spells" VALUES ('Aura of Purity',4,'paladins');
INSERT INTO "Spells" VALUES ('Aura of Vitality',4,'paladins');
INSERT INTO "Spells" VALUES ('Banishment',4,'paladins');
INSERT INTO "Spells" VALUES ('Blinding Smite',4,'paladins');
INSERT INTO "Spells" VALUES ('Compelled Duel',4,'paladins');
INSERT INTO "Spells" VALUES ('Control Water',4,'paladins');
INSERT INTO "Spells" VALUES ('Death Ward:',4,'paladins');
INSERT INTO "Spells" VALUES ('Divination',4,'paladins');
INSERT INTO "Spells" VALUES ('Freedom of Movement:',4,'paladins');
INSERT INTO "Spells" VALUES ('Giant Insect',4,'paladins');
INSERT INTO "Spells" VALUES ('Guardian of Faith',4,'paladins');
INSERT INTO "Spells" VALUES ('Hallucinatory Terrain:',4,'paladins');
INSERT INTO "Spells" VALUES ('Holy Weapon',4,'paladins');
INSERT INTO "Spells" VALUES ('Immovable Object',4,'paladins');
INSERT INTO "Spells" VALUES ('Locate Creature',4,'paladins');
INSERT INTO "Spells" VALUES ('Polymorph',4,'paladins');
INSERT INTO "Spells" VALUES ('Stone Shape',4,'paladins');
INSERT INTO "Spells" VALUES ('Stoneskin',4,'paladins');
INSERT INTO "Spells" VALUES ('Summon Undead',4,'Cleric');
INSERT INTO "Spells" VALUES ('Summon Undead',4,'Paladin');
INSERT INTO "Spells" VALUES ('Wall of Fire',4,'Paladin');
INSERT INTO "Spells" VALUES ('Watery Sphere',4,'Paladin');
INSERT INTO "Spells" VALUES ('Animal Messenger',2,'Druid');
INSERT INTO "Spells" VALUES ('Barkskin',2,'Druid');
INSERT INTO "Spells" VALUES ('Beast Sense',2,'Druid');
INSERT INTO "Spells" VALUES ('Darkvision',2,'Druid');
INSERT INTO "Spells" VALUES ('Enhance Ability',2,'Druid');
INSERT INTO "Spells" VALUES ('Find Traps',2,'Druid');
INSERT INTO "Spells" VALUES ('Flame Blade',2,'Druid');
INSERT INTO "Spells" VALUES ('Flaming Sphere',2,'Druid');
INSERT INTO "Spells" VALUES ('Gust of Wind',2,'Druid');
INSERT INTO "Spells" VALUES ('Heat Metal',2,'Druid');
INSERT INTO "Spells" VALUES ('Hold Person',2,'Druid');
INSERT INTO "Spells" VALUES ('Lesser Restoration',2,'Druid');
INSERT INTO "Spells" VALUES ('Locate Animals or Plants',2,'Druid');
INSERT INTO "Spells" VALUES ('Moonbeam',2,'Druid');
INSERT INTO "Spells" VALUES ('Pass without Trace',2,'Druid');
INSERT INTO "Spells" VALUES ('Protection from Poison:',2,'Druid');
INSERT INTO "Spells" VALUES ('Spike Growth',2,'Druid');
INSERT INTO "Spells" VALUES ('Summon Beast:',2,'Druid');
INSERT INTO "Spells" VALUES ('Warding Wind',2,'Druid');
INSERT INTO "Spells" VALUES ('Web',2,'Druid');
INSERT INTO "Spells" VALUES ('Alter Self',2,'Wizard');
INSERT INTO "Spells" VALUES ('Arcane Lock',2,'Wizard');
INSERT INTO "Spells" VALUES ('Blindness/Deafness',2,'Wizard');
INSERT INTO "Spells" VALUES ('Blur',2,'Wizard');
INSERT INTO "Spells" VALUES ('Cloud of Daggers:',2,'Wizard');
INSERT INTO "Spells" VALUES ('Continual Flame',2,'Wizard');
INSERT INTO "Spells" VALUES ('Darkness',2,'Wizard');
INSERT INTO "Spells" VALUES ('Darkvision',2,'Wizard');
INSERT INTO "Spells" VALUES ('Detect Thoughts',2,'Wizard');
INSERT INTO "Spells" VALUES ('Enlarge/Reduce',2,'Wizard');
INSERT INTO "Spells" VALUES ('Flaming Sphere:',2,'Wizard');
INSERT INTO "Spells" VALUES ('Gentle Repose',2,'Wizard');
INSERT INTO "Spells" VALUES ('Gust of Wind',2,'Wizard');
INSERT INTO "Spells" VALUES ('Hold Person',2,'Wizard');
INSERT INTO "Spells" VALUES ('Invisibility',2,'Wizard');
INSERT INTO "Spells" VALUES ('Knock',2,'Wizard');
INSERT INTO "Spells" VALUES ('Levitate',2,'Wizard');
INSERT INTO "Spells" VALUES ('Locate Object',2,'Wizard');
INSERT INTO "Spells" VALUES ('Magic Mouth',2,'Wizard');
INSERT INTO "Spells" VALUES ('Magic Weapon',2,'Wizard');
INSERT INTO "Spells" VALUES ('Melf''s Acid Arrow:',2,'Wizard');
INSERT INTO "Spells" VALUES ('Mirror Image: ',2,'Wizard');
INSERT INTO "Spells" VALUES ('Misty Step',2,'Wizard');
INSERT INTO "Spells" VALUES (' Magic Aura',2,'Wizard');
INSERT INTO "Spells" VALUES ('Phantasmal Force:',2,'Wizard');
INSERT INTO "Spells" VALUES ('Ray of Enfeeblement',2,'Wizard');
INSERT INTO "Spells" VALUES ('Rope Trick',2,'Wizard');
INSERT INTO "Spells" VALUES ('Scorching Ray:',2,'Wizard');
INSERT INTO "Spells" VALUES ('See Invisibility',2,'Wizard');
INSERT INTO "Spells" VALUES ('Shatter',2,'Wizard');
INSERT INTO "Spells" VALUES ('Spider Climb',2,'Wizard');
INSERT INTO "Spells" VALUES ('Suggestion',2,'Wizard');
INSERT INTO "Spells" VALUES ('Web',2,'Wizard');
INSERT INTO "Spells" VALUES ('Blink',3,'Warlock');
INSERT INTO "Spells" VALUES ('Clairvoyance',3,'Warlock');
INSERT INTO "Spells" VALUES ('Counterspell',3,'Warlock');
INSERT INTO "Spells" VALUES ('Dispel Magic',3,'Warlock');
INSERT INTO "Spells" VALUES ('Feign Death',3,'Warlock');
INSERT INTO "Spells" VALUES ('Fly',3,'Warlock');
INSERT INTO "Spells" VALUES ('Gaseous Form',3,'Warlock');
INSERT INTO "Spells" VALUES ('Hunger of Hadar',3,'Warlock');
INSERT INTO "Spells" VALUES ('Hypnotic Pattern',3,'Warlock');
INSERT INTO "Spells" VALUES ('Magic Circle:',3,'Warlock');
INSERT INTO "Spells" VALUES ('Major Image',3,'Warlock');
INSERT INTO "Spells" VALUES ('Remove Curse',3,'Warlock');
INSERT INTO "Spells" VALUES ('Sleet Storm',3,'Warlock');
INSERT INTO "Spells" VALUES ('Speak with Dead',3,'Warlock');
INSERT INTO "Spells" VALUES ('Tongues',3,'Warlock');
INSERT INTO "Spells" VALUES ('Vampiric Touch',3,'Warlock');
INSERT INTO "Spells" VALUES ('Water Walk:',3,'Warlock');
INSERT INTO "races" VALUES (0,'','','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "races" VALUES (1,'Dragonborn','Medium','30','Humanoid','2',NULL,NULL,NULL,NULL,'1','Common','Draconic',NULL);
INSERT INTO "races" VALUES (2,'Dwarf','Medium','25','Humanoid/Dwarf',NULL,'2',NULL,NULL,NULL,NULL,'Common','Dwarvish',NULL);
INSERT INTO "races" VALUES (3,'Elf','Medium','30','Humanoid/Elf',NULL,NULL,'2',NULL,NULL,NULL,'Common','Elvish',NULL);
INSERT INTO "races" VALUES (4,'High Elf','Medium','30','Humanoid/Elf',NULL,NULL,'2','1',NULL,NULL,'Common','Elvish',NULL);
INSERT INTO "races" VALUES (5,'Wood Elf','Medium','30','Humanoid/Elf',NULL,NULL,'2',NULL,'1',NULL,'Common','Evlish',NULL);
INSERT INTO "races" VALUES (6,'Elf','Medium','30','Humanoid/Dwarf',NULL,NULL,NULL,NULL,NULL,NULL,'Common','Dwarvish',NULL);
INSERT INTO "races" VALUES (7,'Half Elf','Medium','30','Humanoid',NULL,NULL,NULL,NULL,NULL,'2','Common','Elvish','Player''s Choice');
INSERT INTO "races" VALUES (8,'Halfling','Small','25','Humanoid',NULL,NULL,'2',NULL,NULL,NULL,'Common','Halfling',NULL);
INSERT INTO "races" VALUES (9,'Half Orc','Medium','30','Humanoid/Orc','+2','1',NULL,NULL,NULL,NULL,'Common','Orc',NULL);
INSERT INTO "races" VALUES (11,'Tiefling','Medium','30','Humanoid',NULL,NULL,NULL,'1',NULL,'2','Common','Infernal',NULL);
INSERT INTO "classes" VALUES ('Bard');
INSERT INTO "classes" VALUES ('Cleric');
COMMIT;
